### ISSUE TITLE
How can I listen the specific SQS Queue?

### ISSUE THREAD

**Issue by GunjanSkry** [willvincent/adonis-ironium#1]
I want to process SQS message inside the Job when any message arrives in the Queue, The message is sent from outside of the application.

Here is my configuration :
```
service: Env.get('QUEUE_SERVICE', 'aws'),

concurrency: Env.get('QUEUE_CONCURRENCY', 15),

prefix: Env.get('QUEUE_PREFIX', process.NODE_ENV + '-'),

aws: {
  accessKeyId: Env.get('AWS_ACCESS_KEY', 'ChangeMe'),
  secretAccessKey: Env.get('AWS_SECRET_KEY', 'ChangeMe'),
  region: Env.get('AWS_REGION', ''),
  endpoint: Env.get('AWS_ENDPOINT', ''),
  prefix: Env.get('AWS_PREFIX', ''),
  queue: Env.get('AWS_QUEUE', 'Example'),
},
```

**Comment by jpcbarros** [comment]
Have you tried this?
https://github.com/assaf/ironium#processing-a-subset-of-queues

**Comment by n123456789k** [comment]
@willvincent Can we get some more documentation on AWS SQS please, some test env's want to see where I'm going wrong can't seem to find the issue.

**Comment by willvincent** [comment]
@GunjanSkry This is outside the scope of this project... If you need to monitor SQS you'll probably need to set that up differently.  This is really intended for using sqs as the backend for a queue _specific to your adonis application_

You push items into that queue, from the app, and workers _process_ those items.  It's not intended to just arbitrarily monitor an sqs queue and do stuff when messages show up.

Furthermore, this is simply an adonis provider wrapped around ironium.  Questions about how the underlying library works really ought to be directed there.
